### PR TITLE
Add custom DNAT rules to forward DNS to Pi-hole

### PR DESCRIPTION
**Pull request by klutchell**
This allows us to skip host networking.

Change-type: major
Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
Currently resolving `pi.hole` is broken but everything else works. Investigation ongoing...

**Comment by eiddor** [comment]
> Using unbound for upstream will have to be remapped, instead of 127.0.0.1 we need to resolve the bridge IP of the unbound container and inject that before Pi-hole startup. We cannot use hostnames for dnsmasq upstream addresses.

A touch hacky, but can we test for `PIHOLE_DNS_: 127.0.0.1#5053;127.0.0.1#5053` somewhere during init, resolve the `unbound` hostname, and then write the actual container address?

**Comment by eiddor** [comment]
Yeah, as much as I don't like the cons of host networking, I tend to agree that it might not be worth it.  It's definitely a clever workaround, but we're adding some customized complexity to cover for some other complexity, I think.

I may have asked this before, but is there a downside to moving unbound into the pihole container?

**Comment by klutchell** [comment]
> I may have asked this before, but is there a downside to moving unbound into the pihole container?

I don't think you've asked this before, but here are my thoughts:
1. In the Docker world, each container should run one service/process/task. This is why I don't like PADD in the Pi-hole container.
2. Our Unbound image is maintained separately because it takes a long time to compile. We could install from apt but then we are stuck with old releases.
3. Our Unbound image is "distroless", which is awesome!
4. Sharing a stack with Pi-hole would make Unbound less secure.

**Comment by klutchell** [comment]
For now I've published the dnat stuff as an experimental block for reference:
https://github.com/balena-io-playground/dnat-block

**Pull request closed without merging**
