### PR TITLE
Upgrade to Pi-hole v5.8 and FTL v5.8.1

### PR DESCRIPTION
**Pull request by eiddor**
Upgrade to v5.8.1 - https://github.com/pi-hole/docker-pi-hole/releases/tag/v5.8.1

Hold until April 28.

### CODE REVIEW

**Comment by klutchell** [comment]
I like to link to the upstream release tag in my commit or PR message or both:
https://github.com/pi-hole/docker-pi-hole/releases/tag/v5.8

**Comment by eiddor** [comment]
Ah, yes - good call.  Thank you!

**Comment by PromoFaux** [comment]
Just stumbled across this by chance, but hold off on this one for now. There is an issue in the current v5.8 image (see issue thread: https://github.com/pi-hole/docker-pi-hole/issues/834)

Waiting on an approval/merge of this to master then we'll re-tag 5.8:

https://github.com/pi-hole/docker-pi-hole/pull/837

**Comment by klutchell** [comment]
Thanks @PromoFaux, I've got a watch set on that issue now and we'll keep an eye on it.

**Comment by eiddor** [comment]
Thanks for the heads-up @PromoFaux!

**Comment by PromoFaux** [comment]
Retagged, good to go

**Comment by klutchell** [comment]
Thanks Adam! We will probably sit on this PR for another week or so as is my process, but I'll be running it at home and let you know if I see any issues.

**Comment by PromoFaux** [comment]
No problem, you do what you need to do! It was more just to make sure the previous tag didn't break things with your stuff

**Comment by clipse2004** [comment]
Hi guys 

so I tried manually, without any problems :)

**Comment by klutchell** [comment]
@clipse2004 thanks for helping to test this! We will likely merge this week.

**Comment by klutchell** [comment]
In the future you can pop that URL on to the 2nd line of your commit message so it doesn't get cut off.

**Pull request merged**
