### PR TITLE
Update PADD to v3.8.0

### PR DESCRIPTION
**Pull request by eiddor**
https://github.com/pi-hole/PADD/releases/tag/v3.8.0

Signed-off-by: Roddie Hasan <roddie@krweb.net>

### CODE REVIEW

**Comment by eiddor** [comment]
@klutchell Running this now.

**Comment by klutchell** [comment]
Have you seen this on any of your devices? Hopefully it's unrelated to the PADD change, I've reverted to another build to see if the problem goes away.
https://github.com/klutchell/balena-pihole/issues/162

**Comment by klutchell** [comment]
Hopefully unblocked by https://github.com/klutchell/balena-pihole/pull/167

**Comment by klutchell** [comment]
So far so good, will monitor
```
root@pihole:/usr/src/app# du -cksh /var/log/pihole/*
20K     /var/log/pihole/FTL.log
8.0K    /var/log/pihole/pihole.log
28K     total
```

**Comment by klutchell** [comment]
So far so good
```
root@pihole:/usr/src/app# du -cksh /var/log/pihole/*
520K	/var/log/pihole/FTL.log
80K	/var/log/pihole/FTL.log.1
43M	/var/log/pihole/pihole.log
6.6M	/var/log/pihole/pihole.log.1
50M	total
```

**Pull request merged**
