### PR TITLE
Remove custom PADD install as it is included in the base image

### PR DESCRIPTION
**Pull request by klutchell**
See: https://github.com/pi-hole/docker-pi-hole/pull/1105
Depends-on: https://github.com/pi-hole/PADD/pull/302

### CODE REVIEW

**Comment by eiddor** [comment]
Reminder to disable the Renovate tracking of PADD.

**Comment by klutchell** [comment]
Running in production

**Comment by eiddor** [comment]
Same!

**Comment by klutchell** [comment]
Seeing some weirdness in my versions file.
```
root@pihole:/# cat /etc/pihole/versions
CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.14.2
WEB_VERSION=v5.18
FTL_VERSION=v5.20
GITHUB_CORE_VERSION=v5.14.2
GITHUB_WEB_VERSION=v5.18
GITHUB_FTL_VERSION=v5.20
GITHUB_DOCKER_VERSION=2022.12
DOCKER_VERSION=2022.12
CORE_HASH=00345387
GITHUB_CORE_HASH=8d2e023e
WEB_HASH=ad2d4386
GITHUB_WEB_HASH=ad2d4386
FTL_HASH=cba74934
GITHUB_FTL_HASH=cba74934
```
`CORE_HASH` and `GITHUB_CORE_HASH` should be the same and as a result PADD is flagging Pi-hole as out-of-date.

Either that or `CORE_BRANCH` should not be master. It doesn't look like an issue on our end so I may end up opening an issue upstream when I get a chance.

**Comment by eiddor** [comment]
I'm seeing the same stuff in my non-balena Pihole containers.

**Comment by klutchell** [comment]
Seems related to https://github.com/pi-hole/PADD/pull/274

**Comment by eiddor** [comment]
Looks like it will be fixed with https://github.com/pi-hole/PADD/pull/302

**Comment by klutchell** [comment]
> Looks like it will be fixed with [pi-hole/PADD#302](https://github.com/pi-hole/PADD/pull/302)

Good find! I'm tempted to wait until the next release of the Pi-hole image that should include that fix. I don't think there is anything urgent we need from this release?

**Comment by eiddor** [comment]
Yeah, I agree!

**Comment by klutchell** [comment]
Waiting on v2022.12.1 with multiple upstream fixes.

**Pull request merged**
