### PR TITLE
Update pihole/pihole Docker tag to v2022.08

### PR DESCRIPTION
**Pull request by klutchell**
Signed-off-by: Kyle Harding <kyle@balena.io>
Resolves: https://github.com/klutchell/balena-pihole/issues/166

### CODE REVIEW

**Comment by eiddor** [comment]
Did this work for you?  I tried it yesterday to test but got the same error.  I'll test again with this branch.

**Comment by klutchell** [comment]
> Did this work for you? I tried it yesterday to test but got the same error. I'll test again with this branch.

I'm trying it now

**Comment by klutchell** [comment]
Different error, I'm setting up a new device so testing goes faster.
```
 pihole  cont-init: info: running /etc/cont-init.d/05-changer-uid-gid.sh
 pihole  cont-init: info: /etc/cont-init.d/05-changer-uid-gid.sh exited 0
 pihole  cont-init: info: running /etc/cont-init.d/10-custom.sh
 pihole  /package/admin/s6-overlay-3.1.1.2/etc/s6-rc/scripts/cont-init: 14: /etc/cont-init.d/10-custom.sh: not found
 pihole  cont-init: info: /etc/cont-init.d/10-custom.sh exited 127
 pihole  cont-init: warning: some scripts exited nonzero
 ```

**Comment by eiddor** [comment]
Yeah, that's the error that I saw now that I think about it.

It might be related [this](https://github.com/pi-hole/docker-pi-hole/pull/1142) given the number of issues that have been opened.

**Comment by klutchell** [comment]
> Yeah, that's the error that I saw now that I think about it.
> 
> It might be related [this](https://github.com/pi-hole/docker-pi-hole/pull/1142) given the number of issues that have been opened.

That is almost certainly related, I'll have to read that thread when I'm finished with all these meetings.

**Comment by klutchell** [comment]
This PR is working for me now, can you confirm @eiddor ?

**Comment by eiddor** [comment]
Looks good here!

**Pull request merged**
