### PR TITLE
Add optional tailscale service

### PR DESCRIPTION
**Pull request by klutchell**
Signed-off-by: Kyle Harding <kyle@balena.io>
Depends-on: https://github.com/klutchell/balena-pihole/pull/207

### CODE REVIEW

**Comment by klutchell** [comment]
@eiddor this is working for me (both using Tailscale, and with it disabled).

The service is configured with `REQUIRE_AUTH_KEY=true` by default, meaning that if `TS_AUTH_KEY` is not set the service will exit quietly and not loop forever. This makes the service effectively "opt-in".

So it can be used by either providing `TS_AUTH_KEY` or `REQUIRE_AUTH_KEY=false` and using the auth URL from the logs.

The best part of this PR though, is binding to all interfaces by default without port conflicts! LMK if it works for you!

**Comment by eiddor** [comment]
I'll give it a shot this afternoon!

**Comment by klutchell** [comment]
This one is next! The tailscale service should be stopped by default.

**Comment by eiddor** [comment]
```
[Error]      Some services failed to build:
[Error]        Service: tailscale
[Error]          Error: pull access denied for bh.cr/klutchell_blocks/tailscale-armv7hf/1.36.0, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[Info]       Built on arm01
[Error]      Not deploying release.
Remote build failed
```

**Comment by klutchell** [comment]
Oh good catch, I guess I need to make that block public.

**Comment by klutchell** [comment]
Okay, should work now?

**Comment by eiddor** [comment]
Got the new version pushed and I see the tailscale service running because I have `REQUIRE_AUTH_KEY=false`, but I don't see any auth URL or access URL in the logs.  The tailscale service actually has nothing in the log.

image

**Comment by eiddor** [comment]
That screenshot was after restarting the service - Absolutely nothing in the log about tailscale, not with a service filter or even a text filter.

I restarted the entire device and it works now, though - very strange!  I stopped short of installing the app on my Mac, but I was able to auth the device to Tailscale and see it connected.  I flipped `REQUIRE_AUTH_KEY` to `true` and the service is excited as expected.  I think we're good to go! (once you get it merged, I'll test the latest Pihole.

**Pull request merged**
