### PR TITLE
Update Pi-hole to release 2011.12.1

### PR DESCRIPTION
**Pull request by eiddor**
https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.12
https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.12.1

Signed-off-by: Roddie Hasan <roddie@krweb.net>

### CODE REVIEW

**Comment by eiddor** [comment]
Do not merge until at least 12/29.

@klutchell - The Pi-hole container builds and runs fine, but I'm seeing this in the console:

`22.12.21 15:03:18 (-0600)  pihole  ./run: line 20: nc: command not found`

Looks like netcat isn't in the Pi-hole container so the PADD `run` script is breaking.

**Comment by eiddor** [comment]
Fixed it on my system with an `apt-get update && apt-get install netcat` but that might not be the best way to handle it (or is it?)

**Comment by klutchell** [comment]
Looks like they've replaced the old base image with one built from here:
https://github.com/pi-hole/docker-base-images/blob/master/docker-pi-hole-base/Dockerfile

So it's probably safe to add netcat here, but we will have to see if there is anything else missing. I'll have to retest PADD, etc.
https://github.com/klutchell/balena-pihole/blob/64e76fb5b493f635da9022bb75998a528ae76a6e/pihole/Dockerfile#L13

**Comment by klutchell** [comment]
Did you mean to use the same commit message for both commits? This is one case where it makes sense to have 2 unique commit messages.

**Comment by eiddor** [comment]
> So it's probably safe to add netcat here, but we will have to see if there is anything else missing. I'll have to retest PADD, etc.

Done.

> Did you mean to use the same commit message for both commits? This is one case where it makes sense to have 2 unique commit messages.

I did :-) I was preparing for the inevitable "you should squash your commits" message from you since I figured both commits were for the upgrade.

**Comment by eiddor** [comment]
Yes, I will squash these :-)

**Comment by eiddor** [comment]
Ugh.

**Comment by eiddor** [comment]
Trashing this one because I'm terrible at rebasing.

**Pull request closed without merging**
