### PR TITLE
fbcp-block: switch to balenablocks/fbcp

### PR DESCRIPTION
**Pull request by klutchell**
Use the balena fbcp block to handle connected screens.

https://github.com/balenablocks/fbcp

#55

Change-type: major
Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
@rahul-thakoor right now PADD is piped to `/dev/tty1`. Is that still the way to do it with this block?

`/usr/src/app/padd.sh 2> /dev/null > /dev/tty1`

I'm trying to figure out if my screen is white cause nothing is being sent to the framebuffer, or if it's cause my screen is not working with `kedei-v63-mpi3501` like I think it should. I may have to try my other brand of screen.

**Comment by rahul-thakoor** [comment]
hey @klutchell i'm trying this out but it seems that the pihole service keeps crashing looping?

anything i'm missing?

**Comment by rahul-thakoor** [comment]
```
16.01.21 20:25:20 (+0400)  pihole  https://mirror1.malwaredomains.com/files/justdomains
16.01.21 20:25:20 (+0400)  pihole  ::: Testing pihole-FTL DNS: sudo: unable to resolve host 12fb630: Name or service not known
16.01.21 20:25:20 (+0400)  pihole  
16.01.21 20:25:20 (+0400)  pihole  dnsmasq: unknown interface eth0
16.01.21 20:25:20 (+0400)  pihole  [cont-init.d] 20-start.sh: exited 1.
16.01.21 20:25:20 (+0400)  pihole  [cont-finish.d] executing container finish scripts...
16.01.21 20:25:20 (+0400)  pihole  [cont-finish.d] done.
16.01.21 20:25:20 (+0400)  pihole  [s6-finish] waiting for services.
16.01.21 20:25:20 (+0400)  pihole  [s6-finish] sending all processes the TERM signal.
16.01.21 20:25:23 (+0400)  pihole  [s6-finish] sending all processes the KILL signal and exiting.
16.01.21 20:25:24 (+0400) Service exited 'pihole sha256:57173841ae8f0b356bc755eab2da7347dd9d2b9db

**Comment by klutchell** [comment]
@rahul-thakoor 

`dnsmasq: unknown interface eth0`

If you're using wifi make sure to set `DNSMASQ_LISTENING=wlan0` and `INTERFACE=wlan0`.

**Comment by klutchell** [comment]
@rahul-thakoor I suspect that this block does not support my cheap mpi3501-based screen and that's why the `piscreen` overlay works but this block does not. I will try my other screen when I get a chance, but it's my primary DNS at the moment so I don't want to do too much testing on that device.

That being said, I wonder if it's worth breaking support for some screens just to add support for this block? Maybe there's a case where I move the existing fbcp logic to a separate container and keep the dtoverlay requirement.

**Comment by rahul-thakoor** [comment]
pi-hole

It works @klutchell

**Pull request merged**
