### PR TITLE
PADD text display fix

### PR DESCRIPTION
**Pull request by yruoc**
This will correct the display of text in PADD by adding console-setup and executing it at init.

### CODE REVIEW

**Comment by klutchell** [comment]
I'll need some time to test this change myself with the screens I have on hand. Is there something specific I should be looking for with the new behavior vs the old behavior?

**Comment by klutchell** [comment]
@chrisys does this conflict with your [guide](https://www.balena.io/blog/add-a-display-to-your-pi-hole-for-monitoring-and-stats/) at all?

I'm trying to test it but my PiTFT isn't even working with the current build anymore, even when running the previous balenaOS release. I assume the problem is on my end but I haven't been able to test this patch yet.

**Comment by chrisys** [comment]
@klutchell this looks like a better solution than manually editing the cmdline.txt file as I suggested. I will gladly update the guide if it works. You'll probably need to back to 2.38 or earlier to get the TFTs working at this point :/

**Comment by eiddor** [comment]
> @klutchell this looks like a better solution than manually editing the cmdline.txt file as I suggested. I will gladly update the guide if it works. You'll probably need to back to 2.38 or earlier to get the TFTs working at this point :/

I wish I had seen this 10 minutes ago - I couldn't get the latest version to push, so I updated BalenaOS to 2.46.1 and now my display isn't working.  Did I miss something?

**Pull request closed without merging**
