### PR TITLE
Update Pi-hole to release 2021.12.1

### PR DESCRIPTION
**Pull request by eiddor**
Update Pi-hole to release 2021.12.1
https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.12
https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.12.1

Signed-off-by: Roddie Hasan roddie@krweb.net

### CODE REVIEW

**Comment by eiddor** [comment]
Do not merge until 1/1.

**Comment by klutchell** [comment]
Hey dude, thanks for the PR!

I think we actually want to keep the two commits separate in this case, since they serve separate purposes.
- commit 1, bump upstream Pi-hole version, this should look like every other version bump
- commit 2, fix missing packages as a result of upstream changes, this should be rare and is a fix not a bump

So what you have is perfect and does not need to be squashed IMO!

**Comment by klutchell** [comment]
Also it's working for me so far, and I'm keeping an eye on the upstream repo for issues.

**Comment by eiddor** [comment]
Yeah, I thought about it yesterday and I totally agree - So, I went through and tried to squash the two upgrade commits in my first PR while rewording the netcat commit.  It took me six tries and I finally got it, but realized that I'd forgotten to increment the `balena.yml` version and I had the commit messages backwards.  So, I deleted everything and started again, but this time I typo'd the branch name and that typo made it into the commit name via copy/paste.  

So then I deleted everything again and created this one :-)

**Comment by klutchell** [comment]
Superseded by https://github.com/klutchell/balena-pihole/pull/111

**Pull request closed without merging**
