### PR TITLE
Update PADD to 3.6.4

### PR DESCRIPTION
**Pull request by eiddor**
https://github.com/pi-hole/PADD/releases/tag/v3.6.4

Signed-off-by: Roddie Hasan <roddie@krweb.net>

### CODE REVIEW

**Comment by klutchell** [comment]
Deployed to my device for testing.

**Comment by klutchell** [comment]
v3.6.5 is out now: https://github.com/pi-hole/PADD/releases/tag/v3.6.5

**Comment by eiddor** [comment]
3.6.6 now :-) 

https://github.com/pi-hole/PADD/releases/tag/v3.6.6

**Comment by klutchell** [comment]
Superseded by https://github.com/klutchell/balena-pihole/pull/120

**Pull request closed without merging**
