### PR TITLE
Create a tmpfs mount for logs to avoid storage wear

### PR DESCRIPTION
**Pull request by klutchell**
Signed-off-by: Kyle Harding <kyle@balena.io>
Resolves: https://github.com/klutchell/balena-pihole/issues/131

### CODE REVIEW

**Comment by klutchell** [comment]
Your thoughts on this @eiddor?

Essentially if we create a tmpfs mount at `/var/lib/pihole` then logs will be written to memory, and cleared on container recreation or reboot.

Pros:
- does not write logs to SD card, thus extending life
- does not accidentally fill up disk when [bugs](https://github.com/klutchell/balena-pihole/issues/162) are encountered

Cons:
- balena does not allow a custom max tmpfs size right now via compose, so it will default to half of total memory
- logs will not persist, but they are writing to container ephemeral storage now anyway so no change here

I'm tempted to go forward with this even if the tmpfs is larger than we want. This should only be an issue if the logs go crazy and then all of a sudden your device has 50% less memory. On a good day we should never notice the loss of a few hundred megabytes of memory? At least it won't fill your storage and risk bricking your device...

**Comment by eiddor** [comment]
Traveling so I can't test anything, but I think I'm good with this - We should probably have a recommended memory amount for the project just to avoid some of the smaller devices running into issues on day 1.

Is it worth testing this with the bugged version of pihole/PADD just to see the impact when there is a log issue?

**Comment by klutchell** [comment]
> Traveling so I can't test anything, but I think I'm good with this - We should probably have a recommended memory amount for the project just to avoid some of the smaller devices running into issues on day 1.
> 
> Is it worth testing this with the bugged version of pihole/PADD just to see the impact when there is a log issue?

Great idea! Here is a branch with Pi-hole v2022.07.1, PADD v3.8.0 and the tmpfs for logs.
https://github.com/klutchell/balena-pihole/tree/kyle/logging-experiments

It should fill the tmpfs pretty fast and we will see what happens.

**Comment by klutchell** [comment]
The consequences of a full tmpfs seems manageable compared to a full data partition with possible corruption so I'm going to merge this and we can revert it down the road if it adds complications.

**Comment by eiddor** [comment]
Sounds good!

**Pull request merged**
