### PR TITLE
Update pihole/pihole Docker tag to v2023.02.2

### PR DESCRIPTION
**Pull request by klutchell-renovate**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [pihole/pihole](https://togithub.com/pi-hole/docker-pi-hole) | final | patch | `2023.02.1` -> `2023.02.2` |

---

### Release Notes

<details>
<summary>pi-hole/docker-pi-hole</summary>

### [`v2023.02.2`](https://togithub.com/pi-hole/docker-pi-hole/releases/tag/2023.02.2)

[Compare Source](https://togithub.com/pi-hole/docker-pi-hole/compare/2023.02.1...2023.02.2)

#### What's Changed

-   Replace deprecated variables with the correct ones by [@&#8203;rdwebdesign](https://togithub.com/rdwebdesign) in [https://github.com/pi-hole/docker-pi-hole/pull/1320](https://togithub.com/pi-hole/docker-pi-hole/pull/1320)
-   Remove default lightttd from the image https://github.com/pi-hole/docker-pi-hole/commit/4961bf4b1ad394e62b9fee0de60d2be9c84d61b1

**Full Changelog**: https://github.com/pi-hole/docker-pi-hole/compare/2023.02.0...2023.02.2

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by eiddor** [comment]
Should have taken the over.

**Comment by klutchell** [comment]
Welp, I'm glad I didn't bet the mortgage.

**Comment by eiddor** [comment]
(running in production in a minute)

**Comment by klutchell** [comment]
I'm going to hold off until I can test my recent draft PR. Attempting to
identify why we saw some weirdness with tailscale enabled.

This PR isn't going anywhere and may be superseded by next week anyway.

**Pull request merged**
