### PR TITLE
Upgrade Pihole to 2022.04.1

### PR DESCRIPTION
**Pull request by eiddor**
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.1

Signed-off-by: Roddie Hasan <roddie@krweb.net>

### CODE REVIEW

**Comment by eiddor** [comment]
Seems to be stuck in a loop trying to start pihole-FTL:

```
02.04.22 12:01:58 (-0500)  pihole  Starting pihole-FTL (no-daemon) as pihole
02.04.22 12:01:59 (-0500)  pihole  Waiting for FTL on port 4711...
02.04.22 12:02:02 (-0500)  pihole  Stopping pihole-FTL
02.04.22 12:02:02 (-0500)  pihole  pihole-FTL: no process found
02.04.22 12:02:02 (-0500)  pihole  Starting pihole-FTL (no-daemon) as pihole
02.04.22 12:02:04 (-0500)  pihole  Waiting for FTL on port 4711...
02.04.22 12:02:05 (-0500)  pihole  Stopping pihole-FTL
02.04.22 12:02:05 (-0500)  pihole  pihole-FTL: no process found
02.04.22 12:02:05 (-0500)  pihole  Starting pihole-FTL (no-daemon) as pihole
02.04.22 12:02:10 (-0500)  pihole  Waiting for FTL on port 4711...
02.04.22 12:02:10 (-0500)  pihole  Stopping pihole-FTL
02.04.22 12:02:10 (-0500)  pihole  pihole-FTL: no process found
02.04.22 12:02:10 (-0500)  pihole  Starting pihole-FTL (no-daemon) as pihole
```

Any ideas @klutchell?

**Comment by eiddor** [comment]
I think I've got it - testing now.

**Comment by eiddor** [comment]
Nope, no good - I thought it was this: 
image

**Comment by klutchell** [comment]
I tried it on a non-critical device and I'm seeing the same thing. We are already running privileged so we should not need to worry about adding specific capabilities.

**Comment by klutchell** [comment]
I tried running `pihole debug` in the container shell which is super useful and I wish I had tried it in the past. No obvious issues spotted yet though.

**Comment by klutchell** [comment]
I spoke to soon, this is near the end of my FTL logs from `pihole debug`
```
   [2022-04-02 18:31:51.040 3508M] Successfully accessed setupVars.conf
   [2022-04-02 18:31:51.042 3508M] FATAL ERROR in dnsmasq core: failed to create listening socket for 192.168.1.141: Permission denied
   [2022-04-02 18:31:51.081 3508M] ########## FTL terminated after 99ms  (code 1)! ##########
   ```

**Comment by klutchell** [comment]
Based on this thread (current releases of balenaOS are, in fact, using balena engine 20.10 based on docker 20.10)
https://github.com/pi-hole/docker-pi-hole/issues/1019

I was able to resolve the issue by setting the env var `DNSMASQ_USER=root` on my pihole service. This was supposed to be fixed upstream but it seems that's not the case yet. In the meantime we could set this env var in the dockerfile so we aren't blocked.

**Comment by eiddor** [comment]
I wonder if it's caused by the Bullseye base image change.

I'll go ahead and set that ENV now, though this might also be resolved with this one: https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.2beta

**Comment by klutchell** [comment]
I haven't even removed the `DNSMASQ_USER` env var but now I am seeing this error with 2022.04.2
```
 pihole  WARNING: Unable to set capabilities for pihole-FTL.
 pihole           Please ensure that the container has the required capabilities.
 pihole  [cont-init.d] 20-start.sh: exited 1.
````
I can't look into this right now but that error should be easy enough to track down in the upstream.

**Comment by eiddor** [comment]
Yep, I was just about to post the same thing - I even started with the current repo and only changed the version to 04.2/4.2, but I'm still seeing it.

I guess we'll be waiting for 2022.04.3 - I even managed to clean up the commits with rebase!

**Comment by klutchell** [comment]
> I guess we'll be waiting for 2022.04.3 - I even managed to clean up the commits with rebase!

Ya dude, your commits are looking real clean!

**Comment by eiddor** [comment]
Hmmm yeah, I might try that if I get some time this week, too - The question is, how do we run them if the container won't start?

Running them in a working 2022.02.x container gives me nothing:
```
root@pihole:/usr/src/app# /sbin/capsh '==' --print | grep "Current:" | grep -q cap_chown && CAP_STR+=',CAP_CHOWN'
root@pihole:/usr/src/app#     /sbin/capsh '==' --print | grep "Current:" | grep -q cap_net_bind_service && CAP_STR+=',CAP_NET_BIND_SERVICE'
root@pihole:/usr/src/app#     /sbin/capsh '==' --print | grep "Current:" | grep -q cap_net_raw && CAP_STR+=',CAP_NET_RAW'
root@pihole:/usr/src/app#     /sbin/capsh '==' --print | grep "Current:" | grep -q cap_net_admin && CAP_STR+=',CAP_NET_ADMIN' || DHCP_READY='false'
root@pihole:/usr/src/app#     /sbin/capsh '==' --print | grep "Current:" | grep -q cap_sys_nice && CAP_STR+=',CAP_SYS_NICE'  
root@pihole:/usr/src/app# 
```

**Comment by klutchell** [comment]
You'll want to print the value of `CAP_STR` after running those commands.

But that may be a good clue, if `/sbin/capsh '==' --print` is not returning anything then our use of `privileged` (which assigns a number of caps automatically) may not be working with this command and we could try defining them specifically.

**Comment by eiddor** [comment]
Here's `CAP_STR` after the commands:

```
root@pihole:/usr/src/app# set | grep CAP
root@pihole:/usr/src/app#     /sbin/capsh '==' --print | grep "Current:" | grep -q cap_net_bind_service && CAP_STR+=',CAP_NET_BIND_SERVICE'
root@pihole:/usr/src/app#     /sbin/capsh '==' --print | grep "Current:" | grep -q cap_net_raw && CAP_STR+=',CAP_NET_RAW'
root@pihole:/usr/src/app#     /sbin/capsh '==' --print | grep "Current:" | grep -q cap_net_admin && CAP_STR+=',CAP_NET_ADMIN' || DHCP_READY='false'
root@pihole:/usr/src/app#     /sbin/capsh '==' --print | grep "Current:" | grep -q cap_sys_nice && CAP_STR+=',CAP_SYS_NICE'  
root@pihole:/usr/src/app# set | grep CAP
CAP_STR=,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_NET_ADMIN,CAP_SYS_NICE
```

And the entire output of `capsh`:

```
root@pihole:/usr/src/app# /sbin/capsh '==' --print
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read+eip
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=
```

**Comment by klutchell** [comment]
That all looks correct to me, but the upstream function is still failing to check that `CAP_STR` set.

Personally I don't understand how they are using bash in this function and it looks incorrect to me.

- Why not use `if [[ -n ${CAP_STR} ]]; then` instead of `if [[ ${CAP_STR} ]]; then` ?
- Also when is `CAP_STR` every initialised as an array? (eg. `CAP_STR=()` is not found)

All very odd shell scripting IMO but maybe they know something I don't.

Perhaps I will patch that script as part of this PR, and contribute it upstream if my changes work.

**Comment by klutchell** [comment]
I ran the function with bash trace mode to try and narrow down the issue
```
root@pihole:/usr/src/app# fix_capabilities
+ fix_capabilities
+ grep Current:
+ grep -q cap_chown
+ /sbin/capsh == --print
+ grep Current:
+ /sbin/capsh == --print
+ grep -q cap_net_bind_service
+ grep Current:
+ /sbin/capsh == --print
+ grep -q cap_net_raw
+ grep Current:
+ /sbin/capsh == --print
+ grep -q cap_net_admin
+ DHCP_READY=false
+ grep Current:
+ grep -q cap_sys_nice
+ /sbin/capsh == --print
+ [[ -n '' ]]
+ echo 'WARNING: Unable to set capabilities for pihole-FTL.'
WARNING: Unable to set capabilities for pihole-FTL.
+ echo '         Please ensure that the container has the required capabilities.'
         Please ensure that the container has the required capabilities.
+ exit 1
exit
```

**Comment by klutchell** [comment]
Removing `privileged` and replacing it with `cap_add: - NET_ADMIN` gives me expected caps that passes the test.
```
root@pihole:/usr/src/app# /sbin/capsh == --print
+ /sbin/capsh == --print
Current: cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap=eip
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
Ambient set =
Current IAB: cap_chown,cap_dac_override,!cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,!cap_linux_immutable,cap_net_bind_service,!cap_net_broadcast,cap_net_admin,cap_net_raw,!cap_ipc_lock,!cap_ipc_owner,!cap_sys_module,!cap_sys_rawio,cap_sys_chroot,!cap_sys_ptrace,!cap_sys_pacct,!cap_sys_admin,!cap_sys_boot,!cap_sys_nice,!cap_sys_resource,!cap_sys_time,!cap_sys_tty_config,cap_mknod,!cap_lease,cap_audit_write,!cap_audit_control,cap_setfcap,!cap_mac_override,!cap_mac_admin,!cap_syslog,!cap_wake_alarm,!cap_block_suspend,!cap_audit_read,!cap_perfmon,!cap_bpf,!cap_checkpoint_restore
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=
Guessed mode: UNCERTAIN (0)
```
I don't know why privileged isn't assigning more caps on my device, but it's actually better to not use privileged if we don't have to.

**Comment by eiddor** [comment]
Looking good over here.

**Comment by klutchell** [comment]
Confirmed on a Ubuntu desktop environment with Docker 20.10 that privileged containers do not show all the caps expected by the Pi-hole `fix_capabilities` function. Instead it adopts all caps (`=eip`) and specifically removes some.
```
$ docker run --rm -it --privileged alpine sh -c 'apk add --no-cache libcap && capsh --print' | grep Current:
Current: =eip cap_perfmon,cap_bpf,cap_checkpoint_restore-eip
```
```
$ docker run --rm -it alpine sh -c 'apk add --no-cache libcap && capsh --print' | grep Current: 
Current: cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap=eip
```

This explains why the feature wasn't working for us. I'll raise an issue upstream.

**Comment by eiddor** [comment]
Ah-ha - very interesting!  If we specificy NET_ADMIN with privileged, do we get what we need, or does privileged hide everything?

**Comment by klutchell** [comment]
> Ah-ha - very interesting! If we specify NET_ADMIN with privileged, do we get what we need, or does privileged hide everything?

Seems to be the same as privileged.
```
$ docker run --rm -it --privileged --cap-add NET_ADMIN alpine sh -c 'apk add --no-cache libcap && capsh --print' | grep Current: 
Current: =eip cap_perfmon,cap_bpf,cap_checkpoint_restore-eip
```

**Comment by klutchell** [comment]
Added a comment to an existing upstream issue here: https://github.com/pi-hole/docker-pi-hole/issues/1063#issuecomment-1093058049

**Comment by klutchell** [comment]
Upstream PR opened here: https://github.com/pi-hole/docker-pi-hole/pull/1086

**Pull request merged**
