### PR TITLE
Update Pi-hole to 2021.09

### PR DESCRIPTION
**Pull request by klutchell**
The tag format has changed, see these release notes:
https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.09

Resolves: https://github.com/klutchell/balena-pihole/issues/90

Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by clipse2004** [comment]
dude do you update PADD to Version 3.6.2 too?

**Comment by klutchell** [comment]
> dude do you update PADD to Version 3.6.2 too?

@clipse2004 Planning another PR for that, one thing at a time. Though maybe it wouldn't hurt to include it here...

**Comment by eiddor** [comment]
Been testing it since you opened it - No problems here!

(LTGM [I had to Google this])

**Comment by klutchell** [comment]
@eiddor Could you try soaking this release as well?
I've seen no issues so far but I'm also keeping an eye on the [official docker-pihole-repo](https://github.com/pi-hole/docker-pi-hole).

**Comment by eiddor** [comment]
Dear Kyle could you please squash your commits ;-)

**Comment by klutchell** [comment]
Haha, no, I want these ones separate for tracking history.

**Comment by eiddor** [comment]
I'll have to remember that "reason."  haha

**Comment by klutchell** [comment]
I would argue that they are each unique changes that were almost worthy of separate PRs!

Also, because I said so.

**Pull request merged**
