### PR TITLE
Pre-calculate screen size for PADD

### PR DESCRIPTION
**Pull request by klutchell**
Resolves: https://github.com/klutchell/balena-pihole/issues/187

### CODE REVIEW

**Comment by eiddor** [comment]
Running fine here.

**Comment by eiddor** [comment]
Hmmmm the changed seemed to work until the forced push that you did afterwards.  I wonder if I did something wrong.

**Comment by klutchell** [comment]
No, the 2nd push broke for me too. I have some more digging to do this week
for a proper solution.

**Comment by klutchell** [comment]
This is working on both of my devices now. Let me know how it looks for you and we can merge.

**Comment by eiddor** [comment]
Device is upgrading now (there was a transient http error on the hostname task, but that seems to be gone now.)

All good!  

For my own curiosity, is this something we should suggest upstream or are we hitting it due to something specific with our repo?

**Comment by klutchell** [comment]
I opened an [issue](https://github.com/pi-hole/PADD/issues/288) upstream but they haven't run into it and they aren't testing with external screens.

**Pull request merged**
